services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Service directory auto-registration
    Tourze\ResourceManageBundle\Service\:
        resource: '../../Service/'